name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.7'
          extensions: mbstring, xml, curl

      - name: Install dependencies
        run: composer install

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify SSH Key
        run: |
          ssh-add -l
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}

      - name: Deploy to EC2
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            # Ensure proper ownership and permissions
            sudo chown -R $REMOTE_USER:$REMOTE_USER /var/www/html/laravel-project || exit
            sudo chmod -R u+rwX /var/www/html/laravel-project || exit

            # Navigate to project directory
            cd /var/www/html/laravel-project || exit

            # Configure Git to recognize the directory as safe
            git config --global --add safe.directory /var/www/html/laravel-project || exit

            # Pull latest changes from the repository
            git pull origin main || exit

            # Install PHP dependencies
            composer install --no-interaction --prefer-dist --optimize-autoloader || exit

            # Run database migrations
            php artisan migrate --force || exit

            # Restart the web server
            sudo systemctl restart httpd || exit
          EOF
