name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.7'
        extensions: mbstring, xml, curl

    - name: Install dependencies
      run: composer install

    - name: Create .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run tests
      run: php artisan test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
      run: |
        ssh -i "$SSH_PRIVATE_KEY"$REMOTE_USER@$REMOTE_HOST "
        cd /var/www/html/your-laravel-repo && 
        git pull origin main && 
        composer install &&
        php artisan migrate --force &&
        sudo systemctl restart httpd"
